### ISSUE TITLE
Try to use test to feed clinic.js

### ISSUE THREAD

**Issue by rollsappletree** [JointlyTech/cache-candidate#15]
To have better data from clinic, and to be sure that clinic go throught all our codebase we shoud try to use the test suite js to feed clinic.

**Comment by Cadienvan** [comment]
I was able to attach the test suite to bubbleproof, doctor and flame, yet those do not provide meaningful insights as our tests are run against a yet-to-transpile code, so it becomes cluttered, anonymous and unreadable.

On top of that, jest spawns child processes so the output is mainly forks and processes spawned.

@rollsappletree could we close it?
